version: "3"

services:
  je-akka:
    container_name: je-akka
    image: je-akka-node
    build:
      context: .
      dockerfile: AkkaCluster/Dockerfile
    ports:
      - 2555:8081

  je-web:
    container_name: je-web
    image: je-web
    build:
      context: .
      dockerfile: BlazorFrontEnd/Dockerfile
    ports:
      # - 2556:80
      - 2556:8080