scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'je-asteroids-otel-collector:8888'
        - 'je-asteroids-otel-collector:8889'

  - job_name: 'akka_cluster'
    scrape_interval: 10s
    static_configs:
      - targets:
        - 'je-asteroids-akka-1:9090'
        - 'je-asteroids-akka-2:9090'
